name: Go
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - '*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Build Linux
      run: |
        go env -w GOOS=linux && go env -w GOARCH=amd64  && go build -o clean-ns_linux-amd64 -v && chmod a+x clean-ns_linux-amd64
        go env -w GOOS=linux && go env -w GOARCH=arm64  && go build -o clean-ns_linux-arm64 -v && chmod a+x clean-ns_linux-arm64
    - name: Build Darwin
      run: |
        go env -w GOOS=darwin && go env -w GOARCH=amd64  && go build -o clean-ns_darwin-amd64 -v && chmod a+x clean-ns_darwin-amd64
        go env -w GOOS=darwin && go env -w GOARCH=arm64  && go build -o clean-ns_darwin-arm64 -v && chmod a+x clean-ns_darwin-arm64

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "clean-ns_linux-amd64,clean-ns_linux-arm64,clean-ns_darwin-amd64,clean-ns_darwin-arm64"
        bodyFile: "README.md"
        token: ${{ secrets.GITHUB_TOKEN }}
