name: Go
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - '*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Build Linux
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64  go build -o clean-ns_linux-amd64 -v
        CGO_ENABLED=0 GOOS=linux GOARCH=arm64  go build -o clean-ns_linux-arm64 -v
        chmod a+x clean-ns_linux-amd64
        chmod a+x clean-ns_linux-arm64
    - name: Build Darwin
      run: |
        CGO_ENABLED=0 GOOS=darwin GOARCH=amd64  go build -o clean-ns_darwin-amd64 -v
        CGO_ENABLED=0 GOOS=darwin GOARCH=arm64  go build -o clean-ns_darwin-arm64 -v
        chmod a+x clean-ns_darwin-amd64
        chmod a+x clean-ns_darwin-arm64
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "clean-ns_linux-amd64,clean-ns_linux-arm64,clean-ns_darwin-amd64,clean-ns_darwin-arm64"
        bodyFile: "README.md"
        token: ${{ secrets.GITHUB_TOKEN }}
