name: Go
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - '*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go
        - name: Prepare
          id: prepare
          run: |
            TAG=${GITHUB_REF#refs/tags/}
            echo ::set-output name=tag_name::${TAG}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release  --timeout=1h --release-notes=README.md
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        VERSION: ${{ steps.prepare.outputs.tag_name }}
